### ISSUE TITLE
skip-inflation doesn't seem to work

### ISSUE THREAD

**Issue by Pcdejong** [datalogic/scan2deploy-android#1]
Tested with version 1.7.28 (Memor 10 with firmware 1.02.07)

If I set skip-inflation to true the file is still inflated.

Content: I want to directly download an APK file. If I do that the apk file is inflated and can't be installed.

    "deployment": {
        "scheme": "http",
        "host": "download.soti.net",
        "port": 80,
        "path": "/apk/v1370/Datalogic/DatalogicMobiControl1370_1031.apk",
        "ping-timeout": 2000,
        "fetch-timeout": 100000,
	    "skip-inflation": true
    }

**Comment by Pcdejong** [comment]
Quick test with version 1.9.198 gave the same result.

**Comment by codybrookshear** [comment]
Ok, thank you for the report. I've created an internal issue to track this. I'll come back here and provide a link to a new version once fixed.

**Comment by codybrookshear** [comment]
This issue has been resolved in Scan2Deploy [v1.13](https://github.com/datalogic/scan2deploy-android/releases/tag/v1.13.1814).
