### ISSUE TITLE
Send data to activity without using dl_config.exe

### ISSUE THREAD

**Issue by acaliaro** [datalogic/scan2deploy-android#2]
Hi.

Here
[https://datalogic.github.io/scan2deploy/android#third-party-integration](https://datalogic.github.io/scan2deploy/android#third-party-integration)
seems that to use [https://datalogic.github.io/scan2deploy/android#call-startactivity](https://datalogic.github.io/scan2deploy/android#call-startactivity) I have to pass an encoded json (created using dl_config.exe). Is not possibile to use a plain json without encoding? 

var launchIntent = packageManager.getLaunchIntentForPackage("com.datalogic.scan2deploy");
launchIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
launchIntent.putExtra("data", "Bm9uiYc//NWOnA0ZtIrgJ/qy0DCvHR+a1XwUz1sTne8s0KEM9ANwTS0XD4NbIOf/hV0+MM7cOFiZMbUDtO1L4sb4vnJluFbQOEM3phIuCRiBuMtpnh85");
applicationContext.startActivity(launchIntent);

**Comment by codybrookshear** [comment]
Hi @acaliaro, 
Currently, it's not possible to use a plain json without encoding, however, we have an internal task to allow it. It's a low priority issue currently, but thank you for letting us know this would be useful. I will come back here and let you know if and when this is available.

Cody
